import type { Server } from './types'

export const sampleServers: Server[] = [
  {
    id: 'eclipse-reborn',
    gameSlug: 'flyff',
    name: 'Eclipse Reborn',
    players: 24800,
    votes: 8412,
    region: 'Europe',
    mode: 'PvE',
    rating: 4.9,
    description: 'A high-population mythic fantasy world with raid-focused progression and active guild support.',
    status: 'Live',
    trend: '+32%',
  },
  {
    id: 'dragonfall-origins',
    gameSlug: 'flyff',
    name: 'Dragonfall Origins',
    players: 18400,
    votes: 7836,
    region: 'North America',
    mode: 'PvP',
    rating: 4.8,
    description: 'Large-scale PvP arenas, strong faction balance, and regular seasonal campaigns.',
    status: 'Live',
    trend: '+24%',
  },
  {
    id: 'arcane-tides',
    gameSlug: 'ragnarok-online',
    name: 'Arcane Tides',
    players: 15100,
    votes: 7120,
    region: 'South America',
    mode: 'RPG',
    rating: 4.7,
    description: 'Story-heavy progression with deep class design and custom dungeons for long-form play.',
    status: 'Stable',
    trend: '+18%',
  },
  {
    id: 'stormgate-online',
    gameSlug: 'mu-online',
    name: 'Stormgate Online',
    players: 13200,
    votes: 6560,
    region: 'Asia',
    mode: 'PvP',
    rating: 4.6,
    description: 'Competitive battlegrounds and a loyal player base with rapid event rotation.',
    status: 'Live',
    trend: '+14%',
  },
  {
    id: 'abyss-commons',
    gameSlug: 'minecraft',
    name: 'Abyss Commons',
    players: 11700,
    votes: 5984,
    region: 'Europe',
    mode: 'PvE',
    rating: 4.5,
    description: 'A relaxed social MMO with town-building systems and cooperative raids.',
    status: 'Stable',
    trend: '+11%',
  },
]
