import {describe,expect,it,vi}from'vitest'
import {createAdvertisingEndpoints}from'./advertisingEndpoints'
import {applyPalette,GIFEncoder,quantize}from'gifenc'
const sid='123e4567-e89b-42d3-a456-426614174000';const gif=()=>{const rgba=new Uint8Array(468*60*4);for(let i=3;i<rgba.length;i+=4)rgba[i]=255;const palette=quantize(rgba,256),encoder=GIFEncoder();encoder.writeFrame(applyPalette(rgba,palette),468,60,{palette,delay:100});encoder.finish();return encoder.bytes()}
function setup(){const repository={listAdminPlacements:vi.fn().mockResolvedValue([]),moderatePlacement:vi.fn().mockResolvedValue('suspend'),putBanner:vi.fn().mockResolvedValue('stored'),putExclusiveBanner:vi.fn().mockResolvedValue('stored'),submitDonationClaim:vi.fn().mockResolvedValue({outcome:'accepted',claimId:sid}),listPendingDonationClaims:vi.fn().mockResolvedValue([]),moderateDonationClaim:vi.fn().mockResolvedValue('verified'),listOwnedServers:vi.fn().mockResolvedValue([{id:sid,name:'Moonlight',gameSlug:'flyff',gameName:'Flyff'}]),listActivePackages:vi.fn().mockResolvedValue([]),listOwnerDonationClaims:vi.fn().mockResolvedValue([]),listPublic:vi.fn().mockResolvedValue([{id:'ad',serverId:sid,serverName:'Moonlight',bannerId:sid,mediaType:'image/gif',altText:'Moonlight banner',destinationUrl:'https://moonlight.example/',startsAt:'2026-01-01',expiresAt:'2026-01-02'}]),getPublicBanner:vi.fn().mockResolvedValue({bytes:gif(),mediaType:'image/gif'}),getBannerReviewPreview:vi.fn().mockResolvedValue({bytes:new Uint8Array([137,80,78,71]),mediaType:'image/png'}),listPendingBanners:vi.fn().mockResolvedValue([]),moderateBanner:vi.fn().mockResolvedValue('approved')};const deps={allowedOrigins:['https://mmorpgtop100.com'],verifyOwner:vi.fn().mockResolvedValue({uid:'owner'}),verifyTurnstile:vi.fn().mockResolvedValue(true),verifyDonationTurnstile:vi.fn().mockResolvedValue(true),verifyAdmin:vi.fn().mockResolvedValue({uid:'admin'}),deriveOwnerKey:vi.fn().mockResolvedValue(new Uint8Array(32)),deriveModeratorKey:vi.fn().mockResolvedValue(new Uint8Array(32)),rateLimit:vi.fn().mockResolvedValue({success:true}),exclusiveBannerModerationEnabled:false,repository};return{deps,endpoints:createAdvertisingEndpoints(deps)}}
describe('advertising endpoints',()=>{
 it('lists placements only through administrator authorization',async()=>{const c=setup();const response=await c.endpoints.listPlacements(new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}}));expect(response.status).toBe(200);expect(c.deps.verifyAdmin).toHaveBeenCalledOnce();expect(c.deps.repository.listAdminPlacements).toHaveBeenCalledOnce()})
 it('suspends a placement with an auditable operation id',async()=>{const c=setup();const operationId='223e4567-e89b-42d3-a456-426614174000';const response=await c.endpoints.moderatePlacement(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body:JSON.stringify({decision:'suspend',operationId})}),sid);expect(response.status).toBe(200);expect(c.deps.repository.moderatePlacement).toHaveBeenCalledWith(sid,expect.any(Uint8Array),'suspend',operationId)})
 it('lists pending donation claims only after administrator authorization',async()=>{const c=setup();const response=await c.endpoints.listPendingClaims(new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}}));expect(response.status).toBe(200);expect(c.deps.verifyAdmin).toHaveBeenCalledOnce();expect(c.deps.repository.listPendingDonationClaims).toHaveBeenCalledOnce()})
 it('verifies a claim without accepting an amount or currency from the browser',async()=>{const c=setup();const operationId='223e4567-e89b-42d3-a456-426614174000',body=JSON.stringify({decision:'verify',operationId});const response=await c.endpoints.moderateClaim(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body}),sid);expect(response.status).toBe(200);expect(c.deps.repository.moderateDonationClaim).toHaveBeenCalledWith(sid,expect.any(Uint8Array),'verify',null,operationId)})
 it('rejects client-supplied donation amounts before database access',async()=>{const c=setup();const body=JSON.stringify({decision:'verify',operationId:'223e4567-e89b-42d3-a456-426614174000',verifiedAmountMinor:'1'});const response=await c.endpoints.moderateClaim(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body}),sid);expect(response.status).toBe(400);expect(c.deps.repository.moderateDonationClaim).not.toHaveBeenCalled()})
 it('submits a valid donation claim only after owner and Turnstile verification',async()=>{const c=setup();const body=JSON.stringify({serverId:sid,packageCode:'exclusive_7_day',donorReference:'PAYPALREF123',turnstileToken:'challenge-token'});const request=new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json','content-length':String(new TextEncoder().encode(body).length),'cf-connecting-ip':'192.0.2.1'},body});const response=await c.endpoints.submitClaim(request);expect(response.status).toBe(201);expect(c.deps.verifyDonationTurnstile).toHaveBeenCalledWith('challenge-token','192.0.2.1');expect(c.deps.repository.submitDonationClaim).toHaveBeenCalledWith(expect.any(Uint8Array),sid,'exclusive_7_day','PAYPALREF123')})
 it('rejects an unverified donation claim distinctly from account authentication',async()=>{const c=setup();c.deps.verifyDonationTurnstile.mockResolvedValue(false);const body=JSON.stringify({serverId:sid,packageCode:'exclusive_7_day',donorReference:'PAYPALREF123',turnstileToken:'invalid'});const response=await c.endpoints.submitClaim(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body}));expect(response.status).toBe(403);await expect(response.json()).resolves.toMatchObject({message:'Complete the security check again.'});expect(c.deps.repository.submitDonationClaim).not.toHaveBeenCalled()})
 it('rejects unexpected donation claim fields before Turnstile or database access',async()=>{const c=setup();const body=JSON.stringify({serverId:sid,packageCode:'exclusive_7_day',donorReference:'PAYPALREF123',turnstileToken:'token',amount:1});const response=await c.endpoints.submitClaim(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body}));expect(response.status).toBe(400);expect(c.deps.verifyDonationTurnstile).not.toHaveBeenCalled();expect(c.deps.repository.submitDonationClaim).not.toHaveBeenCalled()})
 it('rejects an oversized streamed claim without buffering or database access',async()=>{const c=setup();const response=await c.endpoints.submitClaim(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body:'x'.repeat(1025)}));expect(response.status).toBe(400);expect(c.deps.verifyDonationTurnstile).not.toHaveBeenCalled();expect(c.deps.repository.submitDonationClaim).not.toHaveBeenCalled()})
 it('lists only repository-authorized servers for the verified owner',async()=>{const c=setup();const request=new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}});const response=await c.endpoints.ownerWorkspace(request);expect(response.status).toBe(200);expect(c.deps.repository.listOwnedServers).toHaveBeenCalledWith(expect.any(Uint8Array));await expect(response.json()).resolves.toEqual({ok:true,servers:[{id:sid,name:'Moonlight',gameSlug:'flyff',gameName:'Flyff'}]})})
 it('fails closed with no exclusive upload servers when the eligibility source is unavailable',async()=>{const c=setup();const response=await c.endpoints.advertisingWorkspace(new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}}));expect(response.status).toBe(200);expect(c.deps.repository.listOwnedServers).toHaveBeenCalledOnce();expect(c.deps.repository.listActivePackages).toHaveBeenCalledOnce();expect(c.deps.repository.listOwnerDonationClaims).toHaveBeenCalledOnce();await expect(response.json()).resolves.toMatchObject({exclusiveServers:[]})})
 it('rejects an owner workspace request without an allowed origin before database access',async()=>{const c=setup();const response=await c.endpoints.ownerWorkspace(new Request('https://api.example'));expect(response.status).toBe(403);expect(c.deps.repository.listOwnedServers).not.toHaveBeenCalled()})
 it('rejects an invalid or unverified owner identity before database access',async()=>{const c=setup();c.deps.verifyOwner.mockResolvedValue(null);const request=new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com',authorization:'Bearer invalid'}});const response=await c.endpoints.ownerWorkspace(request);expect(response.status).toBe(401);expect(c.deps.repository.listOwnedServers).not.toHaveBeenCalled()})
 it('rate limits owner workspace requests before identity and database access',async()=>{const c=setup();c.deps.rateLimit.mockResolvedValue({success:false});const request=new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}});const response=await c.endpoints.ownerWorkspace(request);expect(response.status).toBe(429);expect(c.deps.verifyOwner).not.toHaveBeenCalled();expect(c.deps.repository.listOwnedServers).not.toHaveBeenCalled()})
 it('allows a verified server owner with valid Turnstile proof to upload a free banner without any donation claim',async()=>{const c=setup();const bytes=gif();const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','cf-connecting-ip':'192.0.2.1','content-length':String(bytes.length),'x-banner-alt-text':'Moonlight server banner','x-turnstile-token':'challenge-token'},body:bytes});expect((await c.endpoints.upload(request,sid)).status).toBe(201);expect(c.deps.verifyTurnstile).toHaveBeenCalledWith('challenge-token','192.0.2.1');expect(c.deps.repository.putBanner).toHaveBeenCalledOnce()})
 it('fails closed before reading or storing a banner when Turnstile proof is missing or invalid',async()=>{const c=setup();c.deps.verifyTurnstile.mockResolvedValue(false);const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','x-turnstile-token':'invalid'},body:gif()});expect((await c.endpoints.upload(request,sid)).status).toBe(401);expect(c.deps.repository.putBanner).not.toHaveBeenCalled()})
 it('rejects an oversized Turnstile header without calling the verifier',async()=>{const c=setup();const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','x-turnstile-token':'x'.repeat(2049)},body:gif()});expect((await c.endpoints.upload(request,sid)).status).toBe(401);expect(c.deps.verifyTurnstile).not.toHaveBeenCalled();expect(c.deps.repository.putBanner).not.toHaveBeenCalled()})
 it('serves approved banner bytes publicly without authentication',async()=>{const c=setup();const response=await c.endpoints.banner(new Request('https://api.example'),sid);expect(response.status).toBe(200);expect(c.deps.verifyOwner).not.toHaveBeenCalled();expect(c.deps.repository.getPublicBanner).toHaveBeenCalledWith(sid,false);expect(response.headers.get('x-content-type-options')).toBe('nosniff')})
 it('keeps exclusive banners out of all moderation operations while their gate is off',async()=>{const c=setup();const request=new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}});expect((await c.endpoints.listPending(request)).status).toBe(200);expect(c.deps.repository.listPendingBanners).toHaveBeenCalledWith(false);const preview=await c.endpoints.previewPending(request,sid);expect(preview.status).toBe(200);expect(c.deps.repository.getBannerReviewPreview).toHaveBeenCalledWith(sid,false);const operationId='223e4567-e89b-42d3-a456-426614174000';await c.endpoints.moderate(new Request('https://api.example',{method:'POST',headers:{origin:'https://mmorpgtop100.com','content-type':'application/json'},body:JSON.stringify({decision:'approve',operationId})}),sid);expect(c.deps.repository.moderateBanner).toHaveBeenCalledWith(sid,expect.any(Uint8Array),'approve',operationId,false)})
 it('passes an explicit allow scope only after exclusive moderation is enabled',async()=>{const c=setup();c.deps.exclusiveBannerModerationEnabled=true;await c.endpoints.listPending(new Request('https://api.example',{headers:{origin:'https://mmorpgtop100.com'}}));expect(c.deps.repository.listPendingBanners).toHaveBeenCalledWith(true)})
 it('lists game-scoped eligible exclusive ads publicly',async()=>{const c=setup();const response=await c.endpoints.listPublic(new Request('https://api.example'),'flyff');expect(response.status).toBe(200);expect(c.deps.repository.listPublic).toHaveBeenCalledWith('flyff')})
 it('rate limits uploads before authentication',async()=>{const c=setup();c.deps.rateLimit.mockResolvedValue({success:false});const request=new Request('https://api.example',{method:'PUT'});expect((await c.endpoints.upload(request,sid)).status).toBe(429);expect(c.deps.verifyOwner).not.toHaveBeenCalled()})
 it('rejects an oversized streamed body even when content-length claims it is small',async()=>{const c=setup();const body=new Uint8Array(524_289);const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','content-length':'100','x-banner-alt-text':'Moonlight server banner','x-turnstile-token':'challenge-token'},body});expect((await c.endpoints.upload(request,sid)).status).toBe(400);expect(c.deps.repository.putBanner).not.toHaveBeenCalled()})
})
