import {describe,expect,it,vi}from'vitest'
import {createAdvertisingEndpoints}from'./advertisingEndpoints'
import {applyPalette,GIFEncoder,quantize}from'gifenc'
const sid='123e4567-e89b-42d3-a456-426614174000';const gif=()=>{const rgba=new Uint8Array(468*60*4);for(let i=3;i<rgba.length;i+=4)rgba[i]=255;const palette=quantize(rgba,256),encoder=GIFEncoder();encoder.writeFrame(applyPalette(rgba,palette),468,60,{palette,delay:100});encoder.finish();return encoder.bytes()}
function setup(){const repository={putBanner:vi.fn().mockResolvedValue('stored'),listPublic:vi.fn().mockResolvedValue([{id:'ad',serverId:sid,serverName:'Moonlight',bannerId:sid,mediaType:'image/gif',altText:'Moonlight banner',destinationUrl:'https://moonlight.example/',startsAt:'2026-01-01',expiresAt:'2026-01-02'}]),getPublicBanner:vi.fn().mockResolvedValue({bytes:gif(),mediaType:'image/gif'}),listPendingBanners:vi.fn().mockResolvedValue([]),moderateBanner:vi.fn().mockResolvedValue('approved')};const deps={allowedOrigins:['https://mmorpgtop100.com'],verifyOwner:vi.fn().mockResolvedValue({uid:'owner'}),verifyAdmin:vi.fn().mockResolvedValue({uid:'admin'}),deriveOwnerKey:vi.fn().mockResolvedValue(new Uint8Array(32)),deriveModeratorKey:vi.fn().mockResolvedValue(new Uint8Array(32)),rateLimit:vi.fn().mockResolvedValue({success:true}),repository};return{deps,endpoints:createAdvertisingEndpoints(deps)}}
describe('advertising endpoints',()=>{
 it('allows a verified server owner to upload a free banner without any donation claim',async()=>{const c=setup();const bytes=gif();const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','cf-connecting-ip':'192.0.2.1','content-length':String(bytes.length),'x-banner-alt-text':'Moonlight server banner'},body:bytes});expect((await c.endpoints.upload(request,sid)).status).toBe(201);expect(c.deps.repository.putBanner).toHaveBeenCalledOnce()})
 it('serves approved banner bytes publicly without authentication',async()=>{const c=setup();const response=await c.endpoints.banner(new Request('https://api.example'),sid);expect(response.status).toBe(200);expect(c.deps.verifyOwner).not.toHaveBeenCalled();expect(c.deps.repository.getPublicBanner).toHaveBeenCalledWith(sid,false);expect(response.headers.get('x-content-type-options')).toBe('nosniff')})
 it('lists game-scoped eligible exclusive ads publicly',async()=>{const c=setup();const response=await c.endpoints.listPublic(new Request('https://api.example'),'flyff');expect(response.status).toBe(200);expect(c.deps.repository.listPublic).toHaveBeenCalledWith('flyff')})
 it('rate limits uploads before authentication',async()=>{const c=setup();c.deps.rateLimit.mockResolvedValue({success:false});const request=new Request('https://api.example',{method:'PUT'});expect((await c.endpoints.upload(request,sid)).status).toBe(429);expect(c.deps.verifyOwner).not.toHaveBeenCalled()})
 it('rejects an oversized streamed body even when content-length claims it is small',async()=>{const c=setup();const body=new Uint8Array(524_289);const request=new Request('https://api.example',{method:'PUT',headers:{origin:'https://mmorpgtop100.com','content-length':'100','x-banner-alt-text':'Moonlight server banner'},body});expect((await c.endpoints.upload(request,sid)).status).toBe(400);expect(c.deps.repository.putBanner).not.toHaveBeenCalled()})
})
